export const BUS_SEAT_FETCH_REQUEST = "BUS_SEAT_FETCH_REQUEST";
export const BUS_SEAT_FETCH_SUCCESS = "BUS_SEAT_FETCH_SUCCESS";
export const BUS_SEAT_FETCH_FAIL = "BUS_SEAT_FETCH_FAIL";

export const BUS_SEAT_SELECTION_REQUEST = "BUS_SEAT_SELECTION_REQUEST";
export const BUS_SEAT_SELECTION_SUCCESS = "BUS_SEAT_SELECTION_SUCCESS";
export const BUS_SEAT_SELECTION_FAIL = "BUS_SEAT_SELECTION_FAIL";

