export const BUS_SEAT_SELECTION_REQUEST = "BUS_SEAT_SELECTION_REQUEST";
export const BUS_SEAT_SELECTION_SUCCESS = "BUS_SEAT_SELECTION_SUCCESS";
export const BUS_SEAT_SELECTION_FAIL = "BUS_SEAT_SELECTION_FAIL";